import { HttpStatus } from '@nestjs/common';

export const RESPONSE_CODE = {
  SUCCESS: 0,
  PARAM_INVALID: 10001,
  PARAM_MISSING: 10002,
  PARAM_FORMAT_INVALID: 10003,
  UNAUTHORIZED: 20001,
  TOKEN_INVALID: 20002,
  TOKEN_EXPIRED: 20003,
  RESOURCE_NOT_FOUND: 30001,
  CLINIC_NOT_FOUND: 30002,
  TAG_NOT_FOUND: 30003,
  ALREADY_REVIEWED: 40001,
  REVIEW_EXPIRED: 40002,
  ORDER_REQUIRED: 40003,
  TAG_LIMIT_EXCEEDED: 40004,
  ABNORMAL_BEHAVIOR: 40005,
  CLINIC_NOT_CLAIMED: 40006,
  RESPONSE_TOO_LONG: 40007,
  REPEAT_SUBMIT: 40008,
  TOO_MANY_REQUESTS: 40009,
  INTERNAL_SERVER_ERROR: 50001,
  DATABASE_ERROR: 50002,
} as const;

export function getErrorCodeByStatus(status: number) {
  switch (status) {
    case HttpStatus.BAD_REQUEST:
      return RESPONSE_CODE.PARAM_INVALID;
    case HttpStatus.UNAUTHORIZED:
      return RESPONSE_CODE.UNAUTHORIZED;
    case HttpStatus.FORBIDDEN:
      return RESPONSE_CODE.TOKEN_INVALID;
    case HttpStatus.NOT_FOUND:
      return RESPONSE_CODE.RESOURCE_NOT_FOUND;
    case HttpStatus.CONFLICT:
      return RESPONSE_CODE.ALREADY_REVIEWED;
    case HttpStatus.TOO_MANY_REQUESTS:
      return RESPONSE_CODE.TOO_MANY_REQUESTS;
    default:
      return RESPONSE_CODE.INTERNAL_SERVER_ERROR;
  }
}
