import { TagLayer, TagType } from '../entities';

export interface TagSeedItem {
  name: string;
  layer: TagLayer;
  category: string;
  type: TagType;
  weight: number;
  sortOrder: number;
  isUserSelect: number;
  isDisplay: number;
  status: number;
}

export interface ExtraTagOptionSeedItem {
  name: string;
  weight: number;
  sortOrder: number;
  status: number;
}

export const TAG_SEED_DATA: TagSeedItem[] = [
  {
    name: '不乱开药',
    layer: TagLayer.L1,
    category: 'trust',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 1,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '不过度检查',
    layer: TagLayer.L1,
    category: 'trust',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 2,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '解释清楚病情',
    layer: TagLayer.L1,
    category: 'trust',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 3,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '没有隐性收费',
    layer: TagLayer.L1,
    category: 'trust',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 4,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '价格透明',
    layer: TagLayer.L1,
    category: 'value',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 5,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '基础诊疗便宜',
    layer: TagLayer.L1,
    category: 'value',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 6,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '不强推高价项目',
    layer: TagLayer.L1,
    category: 'value',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 7,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '检查合理收费',
    layer: TagLayer.L1,
    category: 'value',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 8,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '医生态度好',
    layer: TagLayer.L1,
    category: 'experience',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 9,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '对宠物耐心',
    layer: TagLayer.L1,
    category: 'experience',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 10,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '环境干净',
    layer: TagLayer.L1,
    category: 'experience',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 11,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '响应快',
    layer: TagLayer.L1,
    category: 'experience',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 12,
    isUserSelect: 1,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '猫专科',
    layer: TagLayer.L2,
    category: 'capability',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 13,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '狗外科',
    layer: TagLayer.L2,
    category: 'capability',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 14,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '皮肤病专长',
    layer: TagLayer.L2,
    category: 'capability',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 15,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '骨科能力',
    layer: TagLayer.L2,
    category: 'capability',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 16,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '急诊能力',
    layer: TagLayer.L2,
    category: 'capability',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 17,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '传染病处理',
    layer: TagLayer.L2,
    category: 'capability',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 18,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '有DR/X光',
    layer: TagLayer.L2,
    category: 'infrastructure',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 19,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '有B超',
    layer: TagLayer.L2,
    category: 'infrastructure',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 20,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '可做手术',
    layer: TagLayer.L2,
    category: 'infrastructure',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 21,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '可住院',
    layer: TagLayer.L2,
    category: 'infrastructure',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 22,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '有化验室',
    layer: TagLayer.L2,
    category: 'infrastructure',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 23,
    isUserSelect: 0,
    isDisplay: 0,
    status: 0,
  },
  {
    name: '有价格争议记录',
    layer: TagLayer.L3,
    category: 'risk',
    type: TagType.Negative,
    weight: 1,
    sortOrder: 24,
    isUserSelect: 0,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '有过医疗纠纷',
    layer: TagLayer.L3,
    category: 'risk',
    type: TagType.Negative,
    weight: 1,
    sortOrder: 25,
    isUserSelect: 0,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '过度推荐手术嫌疑',
    layer: TagLayer.L3,
    category: 'risk',
    type: TagType.Negative,
    weight: 1,
    sortOrder: 26,
    isUserSelect: 0,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '用户投诉较多',
    layer: TagLayer.L3,
    category: 'risk',
    type: TagType.Negative,
    weight: 1,
    sortOrder: 27,
    isUserSelect: 0,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '多次更换医生',
    layer: TagLayer.L3,
    category: 'risk',
    type: TagType.Negative,
    weight: 1,
    sortOrder: 28,
    isUserSelect: 0,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '被推荐次数高',
    layer: TagLayer.L4,
    category: 'social',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 29,
    isUserSelect: 0,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '回头客多',
    layer: TagLayer.L4,
    category: 'social',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 30,
    isUserSelect: 0,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '熟人推荐率高',
    layer: TagLayer.L4,
    category: 'social',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 31,
    isUserSelect: 0,
    isDisplay: 1,
    status: 1,
  },
  {
    name: '本地口碑好',
    layer: TagLayer.L4,
    category: 'social',
    type: TagType.Positive,
    weight: 1,
    sortOrder: 32,
    isUserSelect: 0,
    isDisplay: 1,
    status: 1,
  },
];

export const EXTRA_TAG_OPTION_SEED_DATA: ExtraTagOptionSeedItem[] = [
  { name: '猫更友好', weight: 0.3, sortOrder: 1, status: 1 },
  { name: '狗更友好', weight: 0.3, sortOrder: 2, status: 1 },
  { name: '急诊不错', weight: 0.3, sortOrder: 3, status: 1 },
  { name: '有停车位', weight: 0.3, sortOrder: 4, status: 1 },
  { name: '交通方便', weight: 0.3, sortOrder: 5, status: 1 },
  { name: '可以洗澡', weight: 0.3, sortOrder: 6, status: 1 },
];

export const TAG_SEED_NAMES = TAG_SEED_DATA.map((item) => item.name);
export const EXTRA_TAG_OPTION_SEED_NAMES = EXTRA_TAG_OPTION_SEED_DATA.map(
  (item) => item.name,
);
